# Site settings
name: Anindya Biswas
title: Anindya Biwas | Software Developer
description: Creative-minded software engineer focused on building beautiful, efficient, user friendly solutions
url: https://An1ndya.github.io/
baseurl: ''
email: anindya33046@gmail.com
cover: https://An1ndya.github.io/img/og.png
logo: https://An1ndya.github.io/img/emojis/technologist.png
resume: https://An1ndya.github.io/Professional_CV.pdf
social:
  - title: email
    url: mailto:anindya33046@gmail.com
#  - title: twitter
#    url: https://twitter.com/anindya33046
#  - title: instagram
#    url: https://instagram.com/_anindya__
#  - title: codepen
#    url: http://codepen.io/anindya33046
  - title: github
    url: https://github.com/An1ndya
  - title: linkedin
    url: https://www.linkedin.com/in/anindya33046

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
